import { useEffect, useState } from 'react';
import Head from 'next/head'
import App from '../../App'

export default function Home() {

  const [initialProps, setProps] = useState({
    clientSecret: ''
  });

  let fetchProps = async () => {
    let props = {
      local: true,
      configuration: {
        allowsDelayedPaymentMethods: true,
        merchantDisplayName: 'Example, Inc.',
        allowsPaymentMethodsRequiringShippingAddress: false,
        googlePay: {
          environment: 'Test',
          countryCode: 'US',
          currencyCode: 'US',
        },
      },
      country: 'US',
      type: 'hostedCheckout',
      publishableKey: 'pk_snd_dummy',
      clientSecret: 'pay_dummy_secret_dummy',
    };
    setProps(props)
  }

  useEffect(() => {
    fetchProps()
  }, [])

  return (
    <>
      <Head>
        <title>React Native Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            textarea:focus,
            input:focus {
              outline: none;
            }
          `}
        </style>
      </Head>
      <main style={{ display: 'flex', minHeight: '100vh', width: '100%', overflowX: 'hidden', position: 'relative' }}>
        {initialProps.clientSecret !== '' && <App props={initialProps} />}
      </main>
    </>
  )
}

