let cardNumberInputTestId = "CardNumberInputTestId"
let cvcInputTestId = "CVCInputTestId"
let expiryInputTestId = "ExpiryInputTestId"
let payButtonTestId = "PayButtonTestId"
let sheetCloseButtonTestId = "SheetCloseButtonTestId"
let addNewPaymentMethodTestId = "AddNewPaymentMethodTestId"
let useSavedPaymentMethodsTestId = "UseSavedPaymentMethodsTestId"
let saveCardCheckboxTestId = "SaveCardCheckboxTestId"
// Also on the express-checkout widget's CVC, which reuses SavedPaymentMethod.CVVComponent.
let savedCardCvcInputTestId = "SavedCardCvcInputTestId"
let paymentMethodTabBarTestId = "PaymentMethodTabBarTestId"
let cvcWidgetInputTestId = "CvcWidgetInputTestId"
let payPalButtonTestId = "PayPalButtonTestId"
// Payment method management (PMM) sheet and widget.
let pmmBackButtonTestId = "PmmBackButtonTestId"
let pmmManageButtonTestId = "PmmManageButtonTestId"
let pmmDeleteButtonTestId = "PmmDeleteButtonTestId"
