name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTORELEASE_PAT }}
        run: npx semantic-release
